#!/usr/bin/env python3
"""
Scaffold a new client workflow directory from templates.

Usage:
    python scripts/new_client.py --org-slug my_clinic --workflow-name eligibility_check --flow-type dialout
    python scripts/new_client.py --org-slug my_clinic --workflow-name patient_intake --flow-type dialin

This creates:
    clients/<org_slug>/<workflow_name>/
    ├── __init__.py
    ├── flow_definition.py
    └── services.yaml (reference copy from demo_clinic_alpha)

After running:
1. Customize flow_definition.py with your workflow logic
2. Update services.yaml with your API keys and configuration
3. Register the workflow in the organization's MongoDB document
4. Add frontend routes if needed
"""

import argparse
import sys
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


def snake_to_pascal(name: str) -> str:
    """Convert snake_case to PascalCase. e.g., eligibility_check -> EligibilityCheck"""
    return "".join(word.capitalize() for word in name.split("_"))


def create_dialout_flow(class_name: str, workflow_name: str) -> str:
    """Generate dial-out flow definition content."""
    return f'''"""
{class_name} - Dial-out workflow flow definition.

Generated by new_client.py. Customize this file for your workflow.
"""

from typing import Dict, Any
from pipecat_flows import FlowManager, NodeConfig, FlowsFunctionSchema, ContextStrategy, ContextStrategyConfig
from loguru import logger

from clients.demo_clinic_alpha.dialout_base_flow import DialoutBaseFlow


class {class_name}(DialoutBaseFlow):
    """{class_name} flow with triage support."""

    # ═══════════════════════════════════════════════════════════════════
    # TRIAGE CONFIGURATION
    # ═══════════════════════════════════════════════════════════════════

    TRIAGE_CLASSIFIER_PROMPT = """You are a call classification system for OUTBOUND calls.

HUMAN CONVERSATION (respond "CONVERSATION"):
- Personal greetings: "Hello?", "Hi", "Speaking", "This is [name]"
- Interactive responses: "Who is this?", "How can I help you?"
- Natural speech with pauses and informal tone

IVR SYSTEM (respond "IVR"):
- Menu options: "Press 1 for...", "Press 2 for..."
- Automated instructions: "Please enter your..."
- Hold messages: "Please hold..."

VOICEMAIL SYSTEM (respond "VOICEMAIL"):
- Voicemail greetings: "Please leave a message"
- After-hours messages: "Our office is currently closed"

Output exactly one classification word: CONVERSATION, IVR, or VOICEMAIL."""

    IVR_NAVIGATION_GOAL = """Navigate to speak with a representative.

CALLER INFORMATION (provide when asked):
- TODO: Add relevant caller information fields

NAVIGATION INSTRUCTIONS:
- Choose options related to your purpose
- Say "representative" or "agent" when possible
- Confirm information when asked

Goal: Reach a human representative."""

    VOICEMAIL_MESSAGE_TEMPLATE = """Hi, this is {{caller_name}} calling from {{facility_name}}. Please call us back at your earliest convenience. Thank you."""

    def __init__(self, patient_data: Dict[str, Any], session_id: str = None, flow_manager: FlowManager = None,
                 main_llm=None, classifier_llm=None, context_aggregator=None, transport=None, pipeline=None,
                 organization_id: str = None, cold_transfer_config: Dict[str, Any] = None):
        super().__init__(
            patient_data=patient_data,
            session_id=session_id,
            flow_manager=flow_manager,
            main_llm=main_llm,
            classifier_llm=classifier_llm,
            context_aggregator=context_aggregator,
            transport=transport,
            pipeline=pipeline,
            organization_id=organization_id,
            cold_transfer_config=cold_transfer_config,
        )

    def get_triage_config(self) -> dict:
        """Return triage configuration for this flow."""
        return {{
            "classifier_prompt": self.TRIAGE_CLASSIFIER_PROMPT,
            "ivr_navigation_goal": self.IVR_NAVIGATION_GOAL.format(
                # TODO: Add patient_data field mappings
            ),
            "voicemail_message": self.VOICEMAIL_MESSAGE_TEMPLATE.format(
                caller_name=self._patient_data.get("caller_name", "a representative"),
                facility_name=self._patient_data.get("facility_name", "our facility"),
            ),
        }}

    def _init_domain_state(self):
        """Initialize workflow-specific state fields."""
        # TODO: Initialize state from patient_data
        # Example:
        # self.flow_manager.state["field_name"] = self._patient_data.get("field_name", "")
        pass

    def _get_global_instructions(self) -> str:
        """Return bot persona and behavior instructions."""
        state = self.flow_manager.state
        facility = state.get("facility_name", "Our Facility")
        caller_name = state.get("caller_name", "Representative")

        return f"""You are a Virtual Assistant from {{facility}}, making an outbound call.

# Voice Conversation Style
You are on a phone call. Your responses will be converted to speech:
- Speak naturally and professionally
- Keep responses concise
- Avoid bullet points and markdown formatting

# Your Identity
- Calling on behalf of: {{facility}}
- Caller name: {{caller_name}}

# Guardrails
- Only provide information you have - never guess or invent details
- If asked for information you don't have, say: "I don't have that information available."
- Stay on topic"""

    def create_greeting_node(self) -> NodeConfig:
        """Create greeting node for when a human answers (with or without IVR).

        For outbound calls, we always wait for the receiving party to speak first.
        The transcription that triggered human detection is injected by the handler.
        """
        return NodeConfig(
            name="greeting",
            role_messages=[{{
                "role": "system",
                "content": self._get_global_instructions()
            }}],
            task_messages=[{{
                "role": "system",
                "content": """A human answered. Introduce yourself and state your purpose.

Answer their identification questions using your identity information.
When they indicate they can help, call proceed_to_main_task."""
            }}],
            functions=[
                FlowsFunctionSchema(
                    name="proceed_to_main_task",
                    description="Move to main task after identification.",
                    properties={{}},
                    required=[],
                    handler=self._proceed_to_main_task_handler
                )
            ],
            respond_immediately=False,
            context_strategy=ContextStrategyConfig(strategy=ContextStrategy.RESET)
        )

    def create_main_task_node(self) -> NodeConfig:
        """Create main task node - customize for your workflow."""
        return NodeConfig(
            name="main_task",
            role_messages=[{{
                "role": "system",
                "content": self._get_global_instructions()
            }}],
            task_messages=[{{
                "role": "system",
                "content": """# Goal
TODO: Define your main task instructions here.

# Instructions
- Gather required information
- Record responses using function calls
- When complete, proceed to closing"""
            }}],
            functions=[
                # TODO: Add your workflow-specific function schemas
                FlowsFunctionSchema(
                    name="proceed_to_closing",
                    description="Move to closing when main task is complete.",
                    properties={{}},
                    required=[],
                    handler=self._proceed_to_closing_handler
                )
            ],
            respond_immediately=True
        )

    def create_closing_node(self) -> NodeConfig:
        """Create closing node to end the call."""
        return NodeConfig(
            name="closing",
            role_messages=[{{
                "role": "system",
                "content": self._get_global_instructions()
            }}],
            task_messages=[{{
                "role": "system",
                "content": """Thank the representative and end the call.
Say: "Thank you for your help. Goodbye!"
Then call end_call."""
            }}],
            functions=[
                FlowsFunctionSchema(
                    name="end_call",
                    description="End the conversation after saying goodbye.",
                    properties={{}},
                    required=[],
                    handler=self._end_call_handler
                )
            ],
            respond_immediately=True
        )

    # ═══════════════════════════════════════════════════════════════════
    # HANDLERS
    # ═══════════════════════════════════════════════════════════════════

    async def _proceed_to_main_task_handler(
        self, args: Dict[str, Any], flow_manager: FlowManager
    ) -> tuple[None, "NodeConfig"]:
        logger.info("Flow: greeting → main_task")
        return None, self.create_main_task_node()

    async def _proceed_to_closing_handler(
        self, args: Dict[str, Any], flow_manager: FlowManager
    ) -> tuple[None, "NodeConfig"]:
        logger.info("Flow: main_task → closing")
        return None, self.create_closing_node()
'''


def create_dialin_flow(class_name: str, workflow_name: str) -> str:
    """Generate dial-in flow definition content."""
    return f'''"""
{class_name} - Dial-in workflow flow definition.

Generated by new_client.py. Customize this file for your workflow.
"""

from typing import Dict, Any
from pipecat_flows import FlowManager, NodeConfig, FlowsFunctionSchema
from loguru import logger

from clients.demo_clinic_alpha.dialin_base_flow import DialinBaseFlow


class {class_name}(DialinBaseFlow):
    """{class_name} dial-in flow."""

    def __init__(self, call_data: Dict[str, Any], session_id: str, flow_manager: FlowManager, main_llm,
                 context_aggregator=None, transport=None, pipeline=None, organization_id: str = None,
                 cold_transfer_config: Dict[str, Any] = None):
        super().__init__(call_data, session_id, flow_manager, main_llm, context_aggregator, transport,
                         pipeline, organization_id, cold_transfer_config)

    def _init_domain_state(self):
        """Initialize workflow-specific state fields."""
        state = self.flow_manager.state
        # TODO: Initialize state fields
        # Example:
        # state["field_name"] = self._call_data.get("field_name", "")

    def _get_workflow_type(self) -> str:
        """Return the workflow type for this flow."""
        return "{workflow_name}"

    def _get_global_instructions(self) -> str:
        """Return bot persona and behavior instructions."""
        return f"""You are a helpful assistant for {{self.organization_name}}.

# Voice Conversation Style
You are on a phone call. Your responses will be converted to speech:
- Speak naturally and professionally
- Keep responses concise
- Avoid bullet points and markdown formatting

# Guardrails
- Only provide information you have
- If you don't know something, say so
- Stay on topic"""

    def create_greeting_node(self) -> NodeConfig:
        """Create the initial greeting node."""
        return NodeConfig(
            name="greeting",
            role_messages=[{{
                "role": "system",
                "content": self._get_global_instructions()
            }}],
            task_messages=[{{
                "role": "system",
                "content": """Greet the caller warmly. For example:
"Hello, thank you for calling [organization]. How can I help you today?"

Listen to their request and route appropriately using the available functions."""
            }}],
            functions=[
                FlowsFunctionSchema(
                    name="proceed_to_main_task",
                    description="Handle the caller's main request.",
                    properties={{}},
                    required=[],
                    handler=self._proceed_to_main_task_handler
                ),
                self._request_staff_schema(),
            ],
            respond_immediately=True
        )

    def create_main_task_node(self) -> NodeConfig:
        """Create main task node - customize for your workflow."""
        return NodeConfig(
            name="main_task",
            role_messages=[{{
                "role": "system",
                "content": self._get_global_instructions()
            }}],
            task_messages=[{{
                "role": "system",
                "content": """# Goal
TODO: Define your main task instructions here.

# Instructions
- Help the caller with their request
- Gather any required information
- When complete, proceed to closing"""
            }}],
            functions=[
                # TODO: Add your workflow-specific function schemas
                FlowsFunctionSchema(
                    name="proceed_to_closing",
                    description="Move to closing when done.",
                    properties={{}},
                    required=[],
                    handler=self._proceed_to_closing_handler
                ),
                self._request_staff_schema(),
            ],
            respond_immediately=True
        )

    def create_closing_node(self) -> NodeConfig:
        """Create closing node to end the call."""
        return NodeConfig(
            name="closing",
            role_messages=[{{
                "role": "system",
                "content": self._get_global_instructions()
            }}],
            task_messages=[{{
                "role": "system",
                "content": """Wrap up the call politely.
Ask if there's anything else, then say goodbye.
Call end_call when finished."""
            }}],
            functions=[
                FlowsFunctionSchema(
                    name="end_call",
                    description="End the conversation.",
                    properties={{}},
                    required=[],
                    handler=self._end_call_handler
                )
            ],
            respond_immediately=True
        )

    # ═══════════════════════════════════════════════════════════════════
    # HANDLERS
    # ═══════════════════════════════════════════════════════════════════

    async def _proceed_to_main_task_handler(
        self, args: Dict[str, Any], flow_manager: FlowManager
    ) -> tuple[None, "NodeConfig"]:
        logger.info("Flow: greeting → main_task")
        return None, self.create_main_task_node()

    async def _proceed_to_closing_handler(
        self, args: Dict[str, Any], flow_manager: FlowManager
    ) -> tuple[None, "NodeConfig"]:
        logger.info("Flow: main_task → closing")
        return None, self.create_closing_node()
'''


def create_init_file() -> str:
    """Generate __init__.py content."""
    return '"""Workflow package."""\n'


def create_services_yaml_reference() -> str:
    """Generate services.yaml reference content."""
    return '''# Services configuration for this workflow
# Copy this from clients/demo_clinic_alpha/eligibility_verification/services.yaml
# and customize for your needs.
#
# Environment variables use ${VAR_NAME} syntax.
#
# Example structure:
#
# services:
#   transport:
#     api_key: ${DAILY_API_KEY}
#     phone_number_id: ${DAILY_PHONE_NUMBER_ID}
#
#   stt:
#     api_key: ${DEEPGRAM_API_KEY}
#     model: nova-3
#     eager_eot_threshold: 0.55
#     eot_threshold: 0.65
#
#   llm:
#     provider: openai
#     model: gpt-4o
#     api_key: ${OPENAI_API_KEY}
#     temperature: 0.3
#
#   classifier_llm:  # Optional - for triage/IVR detection
#     provider: groq
#     model: llama-3.3-70b-versatile
#     api_key: ${GROQ_API_KEY}
#
#   tts:
#     provider: cartesia
#     model: sonic-2
#     voice_id: YOUR_VOICE_ID
#     api_key: ${CARTESIA_API_KEY}
#
# cold_transfer:
#   staff_number: sip:+15551234567@sip.daily.co

services:
  # TODO: Configure your services here
  # Reference: clients/demo_clinic_alpha/eligibility_verification/services.yaml
'''


def main():
    parser = argparse.ArgumentParser(
        description="Scaffold a new client workflow directory",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/new_client.py --org-slug acme_clinic --workflow-name insurance_check --flow-type dialout
  python scripts/new_client.py --org-slug acme_clinic --workflow-name appointment_booking --flow-type dialin

After running:
  1. Edit clients/<org>/<workflow>/flow_definition.py to customize the conversation flow
  2. Copy and customize services.yaml from demo_clinic_alpha
  3. Register the workflow in your organization's MongoDB document
  4. Add frontend routes if needed
        """
    )
    parser.add_argument(
        "--org-slug",
        required=True,
        help="Organization slug (e.g., 'acme_clinic'). Use snake_case."
    )
    parser.add_argument(
        "--workflow-name",
        required=True,
        help="Workflow name (e.g., 'eligibility_check'). Use snake_case."
    )
    parser.add_argument(
        "--flow-type",
        required=True,
        choices=["dialout", "dialin"],
        help="Flow type: 'dialout' for outbound calls, 'dialin' for inbound calls"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files"
    )

    args = parser.parse_args()

    # Validate names (should be snake_case)
    for name, value in [("org-slug", args.org_slug), ("workflow-name", args.workflow_name)]:
        if not value.replace("_", "").isalnum():
            print(f"Error: {name} should only contain letters, numbers, and underscores")
            sys.exit(1)
        if value[0].isdigit():
            print(f"Error: {name} should not start with a number")
            sys.exit(1)

    # Create directory structure
    workflow_dir = PROJECT_ROOT / "clients" / args.org_slug / args.workflow_name
    workflow_dir.mkdir(parents=True, exist_ok=True)

    # Generate class name from workflow name
    class_name = snake_to_pascal(args.workflow_name) + "Flow"

    # Files to create
    files = {
        "__init__.py": create_init_file(),
        "flow_definition.py": (
            create_dialout_flow(class_name, args.workflow_name)
            if args.flow_type == "dialout"
            else create_dialin_flow(class_name, args.workflow_name)
        ),
        "services.yaml": create_services_yaml_reference(),
    }

    # Create files
    created = []
    skipped = []
    for filename, content in files.items():
        filepath = workflow_dir / filename
        if filepath.exists() and not args.force:
            skipped.append(filename)
            continue
        filepath.write_text(content)
        created.append(filename)

    # Print summary
    print(f"\n{'='*60}")
    print("Client workflow scaffolded successfully!")
    print(f"{'='*60}")
    print(f"\nDirectory: clients/{args.org_slug}/{args.workflow_name}/")
    print(f"Flow type: {args.flow_type}")
    print(f"Flow class: {class_name}")

    if created:
        print("\nCreated files:")
        for f in created:
            print(f"  - {f}")

    if skipped:
        print("\nSkipped (already exist, use --force to overwrite):")
        for f in skipped:
            print(f"  - {f}")

    print(f"\n{'='*60}")
    print("Next steps:")
    print("{'='*60}")
    print(f"""
1. Customize the flow definition:
   vim clients/{args.org_slug}/{args.workflow_name}/flow_definition.py

2. Copy and configure services.yaml:
   cp clients/demo_clinic_alpha/eligibility_verification/services.yaml \\
      clients/{args.org_slug}/{args.workflow_name}/services.yaml
   vim clients/{args.org_slug}/{args.workflow_name}/services.yaml

3. Register workflow in MongoDB (update your organization document):
   {{
     "workflows": {{
       "{args.workflow_name}": {{
         "enabled": true,
         "patient_schema": {{ ... }}
       }}
     }}
   }}

4. Test the workflow:
   # Start backend locally
   ./dev.sh

   # Create a test patient and initiate a call
""")


if __name__ == "__main__":
    main()
